import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/lib/components/NavBar";

const editorialHeading = localFont({
  src: "../materials/fonts/editorial-today.regular.ttf",
  variable: "--font-heading",
});

const poppinsSubheading = Poppins({
  variable: "--font-subheading",
  subsets: ["latin"],
  weight: ["500"],
});

const poppinsSemiBold = Poppins({
  variable: "--font-body-bold",
  subsets: ["latin"],
  weight: ["600"],
});

const poppinsBody = Poppins({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${editorialHeading.variable} ${poppinsSubheading.variable} ${poppinsSemiBold.variable} ${poppinsBody.className} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
